default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  host: localhost
  user: postgres
  pool: 5

development:
  <<: *default
  database: fuber_development
  password: postgres

test:
  <<: *default
  database: fuber_test
  password: postgres